version: "3"
services:
  api:
    build: ./api
    image: somkiat/demo-api
    user: "0:0"
    ports:
      - 8000:1323
      
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=data
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data"]
      interval: 10s
      timeout: 5s
      retries: 5
  
