apiVersion: v1
kind: Service
metadata:
  name: demo-api
  labels:
    app: api
spec:
  selector:
    app: api

  type: NodePort
  ports:
   - port: 1323
     name: http
     targetPort: 1323
     protocol: TCP
     nodePort: 32500